"""Splink 4.0.16 API contract — VERIFIED against the installed package source at P0.

The public Splink docs site documents Splink 5; several of its calls do not exist
at our pinned 4.0.16. Resolve any disagreement against THIS file, which was
generated by introspecting the installed distribution, not against the website.

Verified 2026-08-30 on splink 4.0.16 / duckdb 1.4.5 / pandas 2.3.3 / py3.14.7.
"""
from splink import Linker, SettingsCreator, DuckDBAPI, block_on, ColumnExpression
import splink.comparison_library as cl

# --- the exact call surface this project uses -------------------------------
# db_api = DuckDBAPI(":temporary:")
# linker = Linker(df, settings=SettingsCreator(...), db_api=db_api)
#
# linker.training.estimate_probability_two_random_records_match(
#     deterministic_matching_rules=[...], recall=<float>, max_rows_limit=1_000_000_000)
# linker.training.estimate_u_using_random_sampling(max_pairs=1e6, seed=SEED)   # <- seed IS supported
# linker.training.estimate_parameters_using_expectation_maximisation(blocking_rule, ...)
#
# df_predict  = linker.inference.predict(threshold_match_weight=-10)
# df_clusters = linker.clustering.cluster_pairwise_predictions_at_threshold(
#                   df_predict, threshold_match_weight=<chosen>)
# metrics     = linker.clustering.compute_graph_metrics(df_predict, df_clusters)
#
# THE TRAP: probability_two_random_records_match defaults to 0.0001 and untrained
# m values yield ZERO matches with NO error. Set a real prior AND run EM.
# Second suspect if predictions are empty: `pip freeze | grep pandas` — a 3.x
# resolve fails identically. Our lockfile pins 2.3.3.
#
# DETERMINISM: EM in 4.0.16 is a deterministic fixed-point iteration (no RNG).
# The only stochastic step is estimate_u_using_random_sampling, which takes a
# seed. Seeded + fixed input => fully deterministic pipeline. This is what makes
# the P6 stability number mean something rather than measuring our own RNG.
SEED = 20260830

__all__ = ["Linker", "SettingsCreator", "DuckDBAPI", "block_on", "ColumnExpression", "cl", "SEED"]
